spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gekkoudb
    username: gekkou
    password: gekkou
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
